"""research planning layer

Revision ID: 18d5e18a097f
Revises: 1e460d99a95b
Create Date: 2026-09-17 15:14:52.303818

Phase 7 (researchos.planning): adds five new tables
(contribution_candidates, contribution_candidate_questions,
dataset_requirements, experimental_designs,
experimental_design_questions) and extends research_questions,
methodology_plans, and novelty_assessments with the new shared
`PlanningApprovalStatus` candidate/approval axis plus structured
planning content and generation provenance. Built entirely on
inspecting the existing Phase 3/6 schema first: `ContributionCandidate`
is a new, distinct entity (not a repurposing of `NoveltyAssessment` —
see docs/PHASE7_RESEARCH_PLANNING.md for why); `MethodologyPlan` is
extended in place, keeping its existing `MethodologyStatus`
(DRAFT/ACTIVE/SUPERSEDED) lifecycle untouched and independent of the
new `planning_status` (human-approval) axis; `DatasetRequirements` and
`ExperimentalDesign` are new planning-only entities, deliberately
distinct from the existing `DatasetRecord`/`Experiment` execution-
tracking entities, which this migration does not touch.

`contribution_candidates.supersedes_id` and `experimental_designs.
supersedes_id` (added during the Phase 7 post-implementation audit
remediation, Finding C) are nullable self-referential foreign keys, each
`UniqueConstraint`-protected so a row can be superseded by at most one
later version — a real, traceable, unbranching lineage for "this is a
revised version of that exact prior row", distinct from an unrelated,
independently-generated row that also happens to exist in the same
project. See `ContributionCandidate`'s docstring in
`researchos.db.models` for the full reasoning.

All five new enum columns use `create_constraint=True` (a real CHECK
constraint), continuing the Phase 4/5/6 practice. The autogenerated
foreign keys onto `contribution_candidates` were given explicit names
(`fk_methodology_plans_contribution_candidate_id`,
`fk_novelty_assessments_contribution_candidate_id`,
`fk_dataset_requirements_methodology_plan_id`,
`fk_experimental_designs_methodology_plan_id`,
`fk_experimental_designs_dataset_requirements_id`) so their
`downgrade()` drop_constraint calls are well-defined — the same fix
applied in the Phase 4/6 migrations.

`evidence_links.subject_type`'s existing CHECK constraint
(`evidencesubjecttype`) is widened by hand below (autogenerate does not
detect CHECK-constraint *value-set* changes on an already-existing enum
column) to admit the five new `EvidenceSubjectType` members this phase
adds — the constraint is dropped and the column re-altered to the new,
9-value `Enum` within the same `batch_alter_table` block, and
`downgrade()` reverses this back to the original 4-value set before
touching anything else, mirroring the same drop-CHECK-before-column-op
ordering the Phase 4/5/6 migrations already had to get right for SQLite
batch mode. No existing data is touched.

Populated-database safety (added during Phase 7 post-implementation
audit remediation): `research_questions.planning_status` and
`methodology_plans.planning_status` are new `NOT NULL` columns on
tables that may already contain rows by the time this migration runs.
Both are added WITH a temporary `server_default='CANDIDATE'` (SQLite's
batch-mode table rebuild uses it to backfill every pre-existing row
during the copy, so the `NOT NULL`/CHECK constraint is satisfied
immediately for old rows without a separate `UPDATE`), then that
`server_default` is dropped in an immediately-following batch step so
the column's default is controlled purely by the ORM/application layer
(`researchos.db.models._enum_column`'s Python-side `default=`) from
that point on — matching every other enum column in this codebase, none
of which carry a server-side default. The final schema this migration
produces is unchanged by this fix (verified: identical to before, save
for the process used to get there); only the migration's safety against
a table that already has rows changes. See
`docs/PHASE7_RESEARCH_PLANNING.md`'s audit-remediation notes for the
reproduction that found this gap and why `novelty_assessments`'s
pre-existing, identically-shaped issue in
`migrations/versions/1e460d99a95b_research_intelligence_layer.py` was
fixed directly in that file rather than here (that revision was already
committed with a fixed, unrelated revision id; editing it in place does
not change what final schema state `1e460d99a95b` represents, so any
environment that already reached that revision is unaffected — only
environments that have not yet run it benefit from the fix).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d5e18a097f'
down_revision: Union[str, None] = '1e460d99a95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_OLD_EVIDENCE_SUBJECT_TYPES = ('ANALYSIS_CLAIM', 'GAP_CANDIDATE', 'NOVELTY_ASSESSMENT', 'NOVELTY_COMPARISON')
_NEW_EVIDENCE_SUBJECT_TYPES = _OLD_EVIDENCE_SUBJECT_TYPES + (
    'RESEARCH_QUESTION', 'CONTRIBUTION_CANDIDATE', 'METHODOLOGY_PLAN', 'DATASET_REQUIREMENTS', 'EXPERIMENTAL_DESIGN',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_candidates',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contribution_type', sa.String(length=100), nullable=True),
    sa.Column('planning_status', sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='planningapprovalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['contribution_candidates.id'], name='fk_contribution_candidates_supersedes_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id', name='uq_contribution_candidate_supersedes')
    )
    with op.batch_alter_table('contribution_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_candidates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_candidates_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('contribution_candidate_questions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contribution_candidate_id', sa.Integer(), nullable=False),
    sa.Column('research_question_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contribution_candidate_id'], ['contribution_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_question_id'], ['research_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_candidate_id', 'research_question_id', name='uq_contribution_candidate_question')
    )
    with op.batch_alter_table('contribution_candidate_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_candidate_questions_contribution_candidate_id'), ['contribution_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_candidate_questions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_candidate_questions_research_question_id'), ['research_question_id'], unique=False)

    op.create_table('dataset_requirements',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('planning_status', sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='planningapprovalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('required_characteristics', sa.Text(), nullable=True),
    sa.Column('source_requirements', sa.Text(), nullable=True),
    sa.Column('inclusion_criteria', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria', sa.Text(), nullable=True),
    sa.Column('annotation_requirements', sa.Text(), nullable=True),
    sa.Column('split_strategy', sa.Text(), nullable=True),
    sa.Column('leakage_considerations', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('reproducibility_requirements', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('methodology_plan_id', sa.Integer(), nullable=True),
    sa.Column('methodology_plan_version', sa.Integer(), nullable=True),
    sa.Column('methodology_plan_status_at_generation', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['methodology_plan_id'], ['methodology_plans.id'], name='fk_dataset_requirements_methodology_plan_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_requirements_methodology_plan_id'), ['methodology_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_requirements_project_id'), ['project_id'], unique=False)

    op.create_table('experimental_designs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('planning_status', sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='planningapprovalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('proposed_method', sa.Text(), nullable=True),
    sa.Column('baselines', sa.JSON(), nullable=True),
    sa.Column('ablation_studies', sa.JSON(), nullable=True),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('comparison_strategy', sa.Text(), nullable=True),
    sa.Column('reproducibility_requirements', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('methodology_plan_id', sa.Integer(), nullable=True),
    sa.Column('methodology_plan_version', sa.Integer(), nullable=True),
    sa.Column('methodology_plan_status_at_generation', sa.String(length=32), nullable=True),
    sa.Column('dataset_requirements_id', sa.Integer(), nullable=True),
    sa.Column('dataset_requirements_status_at_generation', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_requirements_id'], ['dataset_requirements.id'], name='fk_experimental_designs_dataset_requirements_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['methodology_plan_id'], ['methodology_plans.id'], name='fk_experimental_designs_methodology_plan_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['experimental_designs.id'], name='fk_experimental_designs_supersedes_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id', name='uq_experimental_design_supersedes')
    )
    with op.batch_alter_table('experimental_designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimental_designs_dataset_requirements_id'), ['dataset_requirements_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_designs_methodology_plan_id'), ['methodology_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_designs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_designs_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('experimental_design_questions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('experimental_design_id', sa.Integer(), nullable=False),
    sa.Column('research_question_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experimental_design_id'], ['experimental_designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_question_id'], ['research_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experimental_design_id', 'research_question_id', name='uq_experimental_design_question')
    )
    with op.batch_alter_table('experimental_design_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimental_design_questions_experimental_design_id'), ['experimental_design_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_design_questions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimental_design_questions_research_question_id'), ['research_question_id'], unique=False)

    with op.batch_alter_table('methodology_plans', schema=None) as batch_op:
        # server_default is temporary (see the module docstring's
        # "Populated-database safety" note) — backfills any pre-existing
        # row during this table rebuild; dropped again immediately below
        # once every row is guaranteed to have a real value.
        batch_op.add_column(sa.Column(
            'planning_status',
            sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='planningapprovalstatus', native_enum=False, create_constraint=True, length=32),
            nullable=False,
            server_default='CANDIDATE',
        ))
        batch_op.add_column(sa.Column('methodology_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('components', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('assumptions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reproducibility_requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('prompt_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contribution_candidate_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contribution_candidate_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contribution_candidate_status_at_generation', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_methodology_plans_contribution_candidate_id'), ['contribution_candidate_id'], unique=False)
        batch_op.create_foreign_key('fk_methodology_plans_contribution_candidate_id', 'contribution_candidates', ['contribution_candidate_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('methodology_plans', schema=None) as batch_op:
        # Drop the temporary server_default now that every row (old and
        # new) has a real value — matches every other enum column in
        # this codebase, which rely on the ORM's Python-side default only.
        batch_op.alter_column('planning_status', server_default=None)

    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_candidate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_novelty_assessments_contribution_candidate_id'), ['contribution_candidate_id'], unique=False)
        batch_op.create_foreign_key('fk_novelty_assessments_contribution_candidate_id', 'contribution_candidates', ['contribution_candidate_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hypothesis', sa.Text(), nullable=True))
        # server_default is temporary — see the "Populated-database
        # safety" note in this module's docstring.
        batch_op.add_column(sa.Column(
            'planning_status',
            sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='planningapprovalstatus', native_enum=False, create_constraint=True, length=32),
            nullable=False,
            server_default='CANDIDATE',
        ))

    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        # Drop the temporary server_default now that every row has a
        # real value — matches every other enum column in this codebase.
        batch_op.alter_column('planning_status', server_default=None)

    # Widen evidence_links.subject_type's CHECK constraint to admit the
    # five new EvidenceSubjectType members this phase adds. Not detected
    # by autogenerate (it only diffs added/removed columns/tables, not a
    # CHECK constraint's value set) — added by hand.
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_constraint('evidencesubjecttype', type_='check')
        batch_op.alter_column(
            'subject_type',
            existing_type=sa.Enum(*_OLD_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, length=32),
            type_=sa.Enum(*_NEW_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, create_constraint=True, length=32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the evidence_links.subject_type CHECK-constraint widening
    # first, before any of the Phase 7 tables/columns it referenced are
    # dropped.
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_constraint('evidencesubjecttype', type_='check')
        batch_op.alter_column(
            'subject_type',
            existing_type=sa.Enum(*_NEW_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, length=32),
            type_=sa.Enum(*_OLD_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, create_constraint=True, length=32),
            existing_nullable=False,
        )

    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        # See the Phase 4/5/6 migrations' identical fix: batch table
        # recreation carries table-level constraints forward by default,
        # so the CHECK constraint for `planning_status` must be dropped
        # explicitly here or the rebuilt table (missing that column)
        # still references it and CREATE TABLE fails.
        batch_op.drop_constraint('planningapprovalstatus', type_='check')
        batch_op.drop_column('planning_status')
        batch_op.drop_column('hypothesis')

    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_novelty_assessments_contribution_candidate_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_contribution_candidate_id'))
        batch_op.drop_column('contribution_candidate_id')

    with op.batch_alter_table('methodology_plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_methodology_plans_contribution_candidate_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_methodology_plans_contribution_candidate_id'))
        batch_op.drop_column('contribution_candidate_status_at_generation')
        batch_op.drop_column('contribution_candidate_version')
        batch_op.drop_column('contribution_candidate_id')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('prompt_name')
        batch_op.drop_column('model')
        batch_op.drop_column('provider')
        batch_op.drop_column('reproducibility_requirements')
        batch_op.drop_column('risks')
        batch_op.drop_column('assumptions')
        batch_op.drop_column('components')
        batch_op.drop_column('methodology_type')
        # Same CHECK-constraint-before-column-drop fix as above.
        batch_op.drop_constraint('planningapprovalstatus', type_='check')
        batch_op.drop_column('planning_status')

    with op.batch_alter_table('experimental_design_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimental_design_questions_research_question_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_design_questions_project_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_design_questions_experimental_design_id'))

    op.drop_table('experimental_design_questions')
    with op.batch_alter_table('experimental_designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimental_designs_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_designs_project_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_designs_methodology_plan_id'))
        batch_op.drop_index(batch_op.f('ix_experimental_designs_dataset_requirements_id'))

    op.drop_table('experimental_designs')
    with op.batch_alter_table('dataset_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_requirements_methodology_plan_id'))

    op.drop_table('dataset_requirements')
    with op.batch_alter_table('contribution_candidate_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribution_candidate_questions_research_question_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_candidate_questions_project_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_candidate_questions_contribution_candidate_id'))

    op.drop_table('contribution_candidate_questions')
    with op.batch_alter_table('contribution_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribution_candidates_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_candidates_project_id'))

    op.drop_table('contribution_candidates')
    # ### end Alembic commands ###
