"""research intelligence layer

Revision ID: 1e460d99a95b
Revises: a8116c2a3b87
Create Date: 2026-09-17 04:46:42.099937

Phase 6 (researchos.intelligence): adds four new tables
(literature_analyses, analysis_claims, novelty_comparisons,
evidence_links) and extends research_gaps / novelty_assessments with
structured candidate-generation fields and generation provenance
(provider/model/prompt_name/prompt_version). All four new enum columns
use `create_constraint=True` (a real CHECK constraint), continuing the
practice adopted in Phase 4/5 rather than Phase 3's original gap. The
autogenerated `research_question_id` foreign keys on research_gaps and
novelty_assessments were given explicit names
(`fk_research_gaps_research_question_id` /
`fk_novelty_assessments_research_question_id`) so their `downgrade()`
drop_constraint calls are well-defined — the same fix applied in the
Phase 4 migration. No existing column's type changes and no existing
data is touched.

Populated-database safety (added during the Phase 7 post-implementation
audit remediation, editing this already-committed file directly rather
than adding a separate corrective migration): `novelty_assessments.
candidate_status` is a new `NOT NULL` column added to a table that may
already contain rows by the time this migration runs — reproduced
directly during that audit (upgrading a database seeded with a
pre-existing `novelty_assessments` row failed with `NOT NULL constraint
failed`, and left an orphaned `_alembic_tmp_novelty_assessments` table
behind). Fixed the same way as the equivalent, later-discovered issue in
`18d5e18a097f_research_planning_layer.py`: a temporary
`server_default='NOT_ASSESSED'` (matching
`NoveltyCandidateStatus.NOT_ASSESSED`, the model's own Python-side
default) backfills any pre-existing row during the table rebuild, then
is dropped again immediately once every row has a real value. Editing
this file in place (rather than adding a new corrective revision) is
safe here specifically because: (1) this project has never been
deployed or cloned anywhere real — no database anywhere has actually
run this migration outside this repository's own test suite and
scratch verification databases, all of which are recreated from empty
on every run; (2) the fix changes only *how* this migration reaches its
end state for a populated table, not *what* end state it produces —
this revision's id (`1e460d99a95b`) and the final schema it produces
are both unchanged, so any environment that already fully applied this
migration (there are none) would be unaffected either way. No existing
column's type changes and no existing data is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e460d99a95b'
down_revision: Union[str, None] = 'a8116c2a3b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_links',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('literature_item_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('ANALYSIS_CLAIM', 'GAP_CANDIDATE', 'NOVELTY_ASSESSMENT', 'NOVELTY_COMPARISON', name='evidencesubjecttype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SUPPORTS', 'CONTRADICTS', 'RELATED', 'CITES', name='evidencerelationship', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['literature_item_id'], ['literature_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'literature_item_id', 'relationship_type', name='uq_evidence_link_identity')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_links_literature_item_id'), ['literature_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_subject_id'), ['subject_id'], unique=False)

    op.create_table('literature_analyses',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('research_question_id', sa.Integer(), nullable=True),
    sa.Column('research_topic', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('requested_item_ids', sa.JSON(), nullable=False),
    sa.Column('included_item_ids', sa.JSON(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='analysisstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_question_id'], ['research_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('literature_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_literature_analyses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_analyses_research_question_id'), ['research_question_id'], unique=False)

    op.create_table('analysis_claims',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('support_level', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED_CANDIDATE', name='claimsupportlevel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='claimapprovalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['literature_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_claims_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_claims_project_id'), ['project_id'], unique=False)

    op.create_table('novelty_comparisons',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('novelty_assessment_id', sa.Integer(), nullable=False),
    sa.Column('literature_item_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Text(), nullable=True),
    sa.Column('difference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SIMILAR', 'PARTIALLY_DISTINCT', 'DISTINCT', 'UNCLEAR', name='comparisonstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['literature_item_id'], ['literature_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novelty_assessment_id'], ['novelty_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novelty_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novelty_comparisons_literature_item_id'), ['literature_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novelty_comparisons_novelty_assessment_id'), ['novelty_assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novelty_comparisons_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        # server_default is temporary (see "Populated-database safety" in
        # this module's docstring) — backfills any pre-existing row
        # during this table rebuild; dropped again immediately below.
        batch_op.add_column(sa.Column(
            'candidate_status',
            sa.Enum('NOT_ASSESSED', 'POSSIBLY_ALREADY_EXISTING', 'PARTIALLY_DISTINCT', 'POTENTIALLY_DISTINCT', 'INSUFFICIENT_EVIDENCE', 'HUMAN_APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='noveltycandidatestatus', native_enum=False, create_constraint=True, length=32),
            nullable=False,
            server_default='NOT_ASSESSED',
        ))
        batch_op.add_column(sa.Column('unresolved_questions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('novelty_risk', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('research_question_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_gap_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('source_analysis_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('prompt_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_novelty_assessments_research_question_id'), ['research_question_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_novelty_assessments_research_question_id', 'research_questions', ['research_question_id'], ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        # Drop the temporary server_default now that every row has a
        # real value — matches every other enum column in this codebase,
        # which rely on the ORM's Python-side default only.
        batch_op.alter_column('candidate_status', server_default=None)

    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gap_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('affected_research_area', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('evidence_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prior_work_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insufficiency_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('missing_evidence_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('candidate_research_question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('research_question_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_analysis_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('prompt_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_research_gaps_research_question_id'), ['research_question_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_research_gaps_research_question_id', 'research_questions', ['research_question_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_research_gaps_research_question_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_research_gaps_research_question_id'))
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('prompt_name')
        batch_op.drop_column('model')
        batch_op.drop_column('provider')
        batch_op.drop_column('source_analysis_ids')
        batch_op.drop_column('research_question_id')
        batch_op.drop_column('candidate_research_question')
        batch_op.drop_column('missing_evidence_summary')
        batch_op.drop_column('insufficiency_summary')
        batch_op.drop_column('prior_work_summary')
        batch_op.drop_column('evidence_summary')
        batch_op.drop_column('affected_research_area')
        batch_op.drop_column('gap_type')

    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_novelty_assessments_research_question_id', type_='foreignkey')
        # See the Phase 4/5 migrations' identical fix: batch table
        # recreation carries table-level constraints forward by default,
        # so the CHECK constraint for `candidate_status` must be dropped
        # explicitly here or the rebuilt table (missing that column)
        # still references it and CREATE TABLE fails.
        batch_op.drop_constraint('noveltycandidatestatus', type_='check')
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_research_question_id'))
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('prompt_name')
        batch_op.drop_column('model')
        batch_op.drop_column('provider')
        batch_op.drop_column('source_analysis_ids')
        batch_op.drop_column('source_gap_ids')
        batch_op.drop_column('research_question_id')
        batch_op.drop_column('novelty_risk')
        batch_op.drop_column('unresolved_questions')
        batch_op.drop_column('candidate_status')

    with op.batch_alter_table('novelty_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novelty_comparisons_project_id'))
        batch_op.drop_index(batch_op.f('ix_novelty_comparisons_novelty_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_novelty_comparisons_literature_item_id'))

    op.drop_table('novelty_comparisons')
    with op.batch_alter_table('analysis_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_claims_project_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_claims_analysis_id'))

    op.drop_table('analysis_claims')
    with op.batch_alter_table('literature_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_analyses_research_question_id'))
        batch_op.drop_index(batch_op.f('ix_literature_analyses_project_id'))

    op.drop_table('literature_analyses')
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_subject_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_literature_item_id'))

    op.drop_table('evidence_links')
    # ### end Alembic commands ###
