"""analysis and scientific review

Revision ID: 3447e5ed59d4
Revises: 91a24a97a7d4
Create Date: 2026-09-18 13:48:33.560168

Phase 8 (researchos.analysis): adds five new tables (analysis_records,
analysis_inputs, scientific_claims, scientific_claim_analyses,
scientific_reviews). Every new column lives on a brand-new table
created fresh in this migration — exactly like every Phase 8A/8B-1/
8B-2/8B-3 migration before it — so there is nothing to backfill and no
NOT-NULL-without-server_default risk on an existing table.

`Run`/`Metric`/`ArtifactMetadata` (Phase 8B-1/8B-2) and every other
pre-existing table are completely untouched: no column added, no
existing FK altered. `AnalysisRecord` is a new, distinct entity from
Phase 6's `LiteratureAnalysis`/`AnalysisClaim` (which analyze
literature, not execution facts) and from Phase 3's `ExperimentResult`
(a raw recorded measurement, not a computation over one) — see
docs/PHASE8_ANALYSIS_SCIENTIFIC_REVIEW.md for the full "why a new
entity, not a reuse" reasoning.

`analysis_records.supersedes_id` and `scientific_claims.supersedes_id`
and `scientific_reviews.supersedes_id` are nullable self-referential
foreign keys, each `UniqueConstraint`-protected so a row can be
superseded by at most one later version — the same unbranching-lineage
pattern Phase 7/8A/8B-3 established for `ContributionCandidate`/
`ExperimentalDesign`/`DatasetVersion`/`ExperimentSpecification`.
`analysis_inputs.input_id` and (reusing the existing
`evidence_links.subject_type`/`subject_id` polymorphic mechanism)
scientific-claim/analysis-record evidence links are polymorphic by
convention, matching `EvidenceLink.subject_id`'s own established
pattern — no database-level FK is possible across different target
tables; the repository layer validates existence + project ownership
before inserting.

`evidence_links.subject_type`'s existing CHECK constraint is widened by
hand below (autogenerate does not detect CHECK-constraint *value-set*
changes on an already-existing enum column — the same gap noted in
every prior phase's migration) to admit the two new
`EvidenceSubjectType` members this phase adds (`SCIENTIFIC_CLAIM`,
`ANALYSIS_RECORD`). No existing data is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3447e5ed59d4'
down_revision: Union[str, None] = '91a24a97a7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_OLD_EVIDENCE_SUBJECT_TYPES = (
    'ANALYSIS_CLAIM', 'GAP_CANDIDATE', 'NOVELTY_ASSESSMENT', 'NOVELTY_COMPARISON',
    'RESEARCH_QUESTION', 'CONTRIBUTION_CANDIDATE', 'METHODOLOGY_PLAN', 'DATASET_REQUIREMENTS',
    'EXPERIMENTAL_DESIGN', 'DATASET_VERSION', 'EXPERIMENT_SPECIFICATION',
)
_NEW_EVIDENCE_SUBJECT_TYPES = _OLD_EVIDENCE_SUBJECT_TYPES + ('SCIENTIFIC_CLAIM', 'ANALYSIS_RECORD')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=200), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'NOT_COMPARABLE', name='analysisrecordstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('software_versions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['analysis_records.id'], name='fk_analysis_records_supersedes_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id', name='uq_analysis_record_supersedes')
    )
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_records_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_records_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('scientific_claims',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'INSUFFICIENT_EVIDENCE', 'CONTRADICTED', 'NOT_ASSESSABLE', name='claimstrength', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='claimapprovalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['scientific_claims.id'], name='fk_scientific_claims_supersedes_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id', name='uq_scientific_claim_supersedes')
    )
    with op.batch_alter_table('scientific_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_claims_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_claims_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('analysis_inputs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('analysis_record_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.Enum('RUN', 'METRIC', 'ARTIFACT', name='analysisinputtype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_record_id'], ['analysis_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_record_id', 'input_type', 'input_id', name='uq_analysis_input_identity')
    )
    with op.batch_alter_table('analysis_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_inputs_analysis_record_id'), ['analysis_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_inputs_input_id'), ['input_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_inputs_project_id'), ['project_id'], unique=False)

    op.create_table('scientific_claim_analyses',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('analysis_record_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_record_id'], ['analysis_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['scientific_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'analysis_record_id', name='uq_scientific_claim_analysis')
    )
    with op.batch_alter_table('scientific_claim_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_claim_analyses_analysis_record_id'), ['analysis_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_claim_analyses_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_claim_analyses_project_id'), ['project_id'], unique=False)

    op.create_table('scientific_reviews',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CANDIDATE', 'NEEDS_MORE_EVIDENCE', 'READY_FOR_HUMAN_REVIEW', 'HUMAN_APPROVED', 'REJECTED', name='scientificreviewstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['scientific_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['scientific_reviews.id'], name='fk_scientific_reviews_supersedes_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersedes_id', name='uq_scientific_review_supersedes')
    )
    with op.batch_alter_table('scientific_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_reviews_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_reviews_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_reviews_supersedes_id'), ['supersedes_id'], unique=False)

    # Widen evidence_links.subject_type's CHECK constraint to admit the
    # two new EvidenceSubjectType members this phase adds. Not detected
    # by autogenerate — added by hand.
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_constraint('evidencesubjecttype', type_='check')
        batch_op.alter_column(
            'subject_type',
            existing_type=sa.Enum(*_OLD_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, length=32),
            type_=sa.Enum(*_NEW_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, create_constraint=True, length=32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the evidence_links.subject_type CHECK-constraint widening
    # first, before any of this phase's tables it referenced are dropped.
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_constraint('evidencesubjecttype', type_='check')
        batch_op.alter_column(
            'subject_type',
            existing_type=sa.Enum(*_NEW_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, length=32),
            type_=sa.Enum(*_OLD_EVIDENCE_SUBJECT_TYPES, name='evidencesubjecttype', native_enum=False, create_constraint=True, length=32),
            existing_nullable=False,
        )

    with op.batch_alter_table('scientific_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_reviews_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_reviews_project_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_reviews_claim_id'))

    op.drop_table('scientific_reviews')
    with op.batch_alter_table('scientific_claim_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_claim_analyses_project_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_claim_analyses_claim_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_claim_analyses_analysis_record_id'))

    op.drop_table('scientific_claim_analyses')
    with op.batch_alter_table('analysis_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_inputs_project_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_inputs_input_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_inputs_analysis_record_id'))

    op.drop_table('analysis_inputs')
    with op.batch_alter_table('scientific_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_claims_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_claims_project_id'))

    op.drop_table('scientific_claims')
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_records_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_records_method'))

    op.drop_table('analysis_records')
    # ### end Alembic commands ###
