"""initial schema

Revision ID: 8eba82f8bdd1
Revises: 
Create Date: 2026-09-17 03:21:02.753707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eba82f8bdd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='approvaldecision', native_enum=False, length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_project_id'), ['project_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)

    op.create_table('dataset_records',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('path_or_uri', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('split_information', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_dataset_project_name_version')
    )
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_records_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='experimentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('code_version', sa.String(length=255), nullable=True),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('hardware', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('journal_candidates',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'SHORTLISTED', 'SUBMITTED', 'REJECTED', 'ACCEPTED', name='journalcandidatestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_candidates_project_id'), ['project_id'], unique=False)

    op.create_table('literature_items',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('evidence_status', sa.Enum('UNREVIEWED', 'REVIEWED', 'RELEVANT', 'NOT_RELEVANT', name='evidencestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'doi', name='uq_literature_project_doi')
    )
    with op.batch_alter_table('literature_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_literature_items_project_id'), ['project_id'], unique=False)

    op.create_table('manuscripts',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFTING', 'IN_REVIEW', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'PUBLISHED', name='manuscriptstatus', native_enum=False, length=32), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_manuscript_project_version')
    )
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuscripts_project_id'), ['project_id'], unique=False)

    op.create_table('methodology_plans',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', name='methodologystatus', native_enum=False, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_methodology_project_version')
    )
    with op.batch_alter_table('methodology_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_methodology_plans_project_id'), ['project_id'], unique=False)

    op.create_table('novelty_assessments',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED_NOVEL', 'NOT_NOVEL', 'INCONCLUSIVE', name='noveltystatus', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novelty_assessments_project_id'), ['project_id'], unique=False)

    op.create_table('research_gaps',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'VALIDATED', 'REJECTED', name='gapstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_gaps_project_id'), ['project_id'], unique=False)

    op.create_table('research_ideas',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('research_question', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'EXPLORING', 'ACCEPTED', 'REJECTED', 'ARCHIVED', name='ideastatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_ideas_project_id'), ['project_id'], unique=False)

    op.create_table('research_questions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'DROPPED', name='questionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_questions_project_id'), ['project_id'], unique=False)

    op.create_table('experiment_results',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_results_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_results_metric_name'), ['metric_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_results_metric_name'))
        batch_op.drop_index(batch_op.f('ix_experiment_results_experiment_id'))

    op.drop_table('experiment_results')
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_questions_project_id'))

    op.drop_table('research_questions')
    with op.batch_alter_table('research_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_ideas_project_id'))

    op.drop_table('research_ideas')
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_gaps_project_id'))

    op.drop_table('research_gaps')
    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_project_id'))

    op.drop_table('novelty_assessments')
    with op.batch_alter_table('methodology_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methodology_plans_project_id'))

    op.drop_table('methodology_plans')
    with op.batch_alter_table('manuscripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manuscripts_project_id'))

    op.drop_table('manuscripts')
    with op.batch_alter_table('literature_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_items_project_id'))

    op.drop_table('literature_items')
    with op.batch_alter_table('journal_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_candidates_project_id'))

    op.drop_table('journal_candidates')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_records_project_id'))

    op.drop_table('dataset_records')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_project_id'))

    op.drop_table('approvals')
    op.drop_table('research_projects')
    # ### end Alembic commands ###
