"""evidence layer literature extensions

Revision ID: a8116c2a3b87
Revises: e633d3930fa8
Create Date: 2026-09-17 04:02:33.620907

Phase 5 (researchos.evidence): extends `literature_items` with
retrieval/provenance/normalization columns (source_record_id, publisher,
publication_date, document_type, citation_count, keywords, external_ids,
raw_metadata, retrieved_at, record_status, metadata_completeness,
duplicate_of_id) and adds `literature_matches` for recording explained
(candidate) duplicate relationships. No existing column's type changes
and no existing data is touched. The autogenerated `duplicate_of_id`
foreign key was given an explicit name (`fk_literature_items_duplicate_of_id`)
so its `downgrade()` drop_constraint call is well-defined.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8116c2a3b87'
down_revision: Union[str, None] = 'e633d3930fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature_matches',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('literature_item_id', sa.Integer(), nullable=False),
    sa.Column('matched_item_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('DOI', 'SOURCE_ID', 'TITLE_AUTHOR_YEAR', name='matchtype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['literature_item_id'], ['literature_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_item_id'], ['literature_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('literature_item_id', 'matched_item_id', name='uq_literature_match_pair')
    )
    with op.batch_alter_table('literature_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_literature_matches_literature_item_id'), ['literature_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_matches_matched_item_id'), ['matched_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_matches_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('literature_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_record_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('publication_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('citation_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('external_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('raw_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('record_status', sa.Enum('VERIFIED_SOURCE_RECORD', 'PARTIAL_METADATA', 'SOURCE_ERROR', 'NOT_FOUND', 'DUPLICATE_CANDIDATE', name='recordstatus', native_enum=False, create_constraint=True, length=32), nullable=False))
        batch_op.add_column(sa.Column('metadata_completeness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_literature_items_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_items_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_unique_constraint('uq_literature_project_source_record', ['project_id', 'source', 'source_record_id'])
        batch_op.create_foreign_key(
            'fk_literature_items_duplicate_of_id', 'literature_items', ['duplicate_of_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('literature_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_literature_items_duplicate_of_id', type_='foreignkey')
        batch_op.drop_constraint('uq_literature_project_source_record', type_='unique')
        # Batch table-recreation carries table-level constraints forward
        # by default; the CHECK constraint for `record_status` must be
        # dropped explicitly here, or the rebuilt table (missing that
        # column) still references it and CREATE TABLE fails.
        batch_op.drop_constraint('recordstatus', type_='check')
        batch_op.drop_index(batch_op.f('ix_literature_items_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_literature_items_duplicate_of_id'))
        batch_op.drop_column('duplicate_of_id')
        batch_op.drop_column('metadata_completeness')
        batch_op.drop_column('record_status')
        batch_op.drop_column('retrieved_at')
        batch_op.drop_column('raw_metadata')
        batch_op.drop_column('external_ids')
        batch_op.drop_column('keywords')
        batch_op.drop_column('citation_count')
        batch_op.drop_column('document_type')
        batch_op.drop_column('publication_date')
        batch_op.drop_column('publisher')
        batch_op.drop_column('source_record_id')

    with op.batch_alter_table('literature_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_matches_project_id'))
        batch_op.drop_index(batch_op.f('ix_literature_matches_matched_item_id'))
        batch_op.drop_index(batch_op.f('ix_literature_matches_literature_item_id'))

    op.drop_table('literature_matches')
    # ### end Alembic commands ###
