"""execution foundation

Revision ID: b03b320a103c
Revises: 984437859de2
Create Date: 2026-09-18 01:56:46.582069

Phase 8B-1 (researchos.execution): adds three new tables
(environment_snapshots, runs, artifact_metadata). Every new column
lives on a brand-new table created fresh in this migration — exactly
like `984437859de2` before it — so there is nothing to backfill and no
NOT-NULL-without-server_default risk on an existing table.

`Experiment`/`ExperimentResult` (Phase 3), `ExperimentSpecification`/
`DatasetVersion` (Phase 8A), and every other pre-existing table are
completely untouched: no column added, no CHECK constraint widened, no
existing FK altered. `Run` is a new, distinct entity representing one
actual execution instance — `Experiment` (already-existing) remains
the scientific concept; `Experiment 1:N Run` (see
docs/PHASE8B1_EXECUTION_FOUNDATION.md for the full "Run != Experiment"
reasoning).

`runs.experiment_specification_id` / `runs.dataset_version_id` /
`runs.environment_snapshot_id` are all nullable, `ondelete='SET NULL'`
foreign keys — a `Run` outlives the upstream row it referenced (its own
`*_version`/`*_status_at_execution`/`dataset_fingerprint`/
`configuration_snapshot` snapshot columns already carry everything
needed to know what was actually used, so losing the live FK loses
nothing). `runs.experiment_id` is the one required, `ondelete='CASCADE'`
FK — a `Run` cannot outlive the `Experiment` it is one execution
instance of, matching `experiment_results.experiment_id`'s existing
cascade convention.

`environment_snapshots` deliberately has NO `project_id` column — it is
a content-addressable table (`UniqueConstraint` on `environment_hash`)
describing a physical/virtual machine's software stack, which is not a
per-project fact; the same snapshot row is legitimately shared by
`Run`s across different projects. See `EnvironmentSnapshot`'s docstring
in `researchos.db.models` for the full reasoning.

Three new enum columns (`runstatus` on `runs.status`,
`executionbackend` on `runs.execution_backend`, `artifacttype` on
`artifact_metadata.artifact_type`) all use `create_constraint=True` (a
real CHECK constraint), continuing the Phase 4/5/6/7/8A practice. No
existing data is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03b320a103c'
down_revision: Union[str, None] = '984437859de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_snapshots',
    sa.Column('environment_hash', sa.String(length=64), nullable=False),
    sa.Column('os_name', sa.String(length=200), nullable=True),
    sa.Column('os_version', sa.String(length=200), nullable=True),
    sa.Column('architecture', sa.String(length=100), nullable=True),
    sa.Column('python_version', sa.String(length=100), nullable=True),
    sa.Column('pytorch_version', sa.String(length=100), nullable=True),
    sa.Column('torchvision_version', sa.String(length=100), nullable=True),
    sa.Column('cuda_version', sa.String(length=100), nullable=True),
    sa.Column('cudnn_version', sa.String(length=100), nullable=True),
    sa.Column('gpu_name', sa.String(length=500), nullable=True),
    sa.Column('gpu_driver_version', sa.String(length=100), nullable=True),
    sa.Column('package_versions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_hash', name='uq_environment_snapshot_hash')
    )
    with op.batch_alter_table('environment_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_snapshots_environment_hash'), ['environment_hash'], unique=False)

    op.create_table('runs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('experiment_specification_id', sa.Integer(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('environment_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='runstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('execution_backend', sa.Enum('LOCAL_PYTHON', 'DOCKER', 'REMOTE_GPU', 'SLURM', 'CLOUD', name='executionbackend', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('execution_target', sa.JSON(), nullable=True),
    sa.Column('experiment_specification_version', sa.Integer(), nullable=True),
    sa.Column('experiment_specification_status_at_execution', sa.String(length=32), nullable=True),
    sa.Column('configuration_hash', sa.String(length=64), nullable=True),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=True),
    sa.Column('dataset_version_version', sa.Integer(), nullable=True),
    sa.Column('dataset_version_status_at_execution', sa.String(length=32), nullable=True),
    sa.Column('dataset_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('code_repository', sa.String(length=2000), nullable=True),
    sa.Column('code_commit', sa.String(length=64), nullable=True),
    sa.Column('code_branch', sa.String(length=500), nullable=True),
    sa.Column('working_tree_clean', sa.Boolean(), nullable=True),
    sa.Column('code_provenance_unavailable_reason', sa.String(length=200), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_reference', sa.String(length=2000), nullable=True),
    sa.Column('stderr_reference', sa.String(length=2000), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name='fk_runs_dataset_version_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_snapshot_id'], ['environment_snapshots.id'], name='fk_runs_environment_snapshot_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_specification_id'], ['experiment_specifications.id'], name='fk_runs_experiment_specification_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_configuration_hash'), ['configuration_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_environment_snapshot_id'), ['environment_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_experiment_specification_id'), ['experiment_specification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)

    op.create_table('artifact_metadata',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('STDOUT', 'STDERR', 'CHECKPOINT', 'MODEL', 'PLOT', 'LOG', 'RESULT', 'OTHER', name='artifacttype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reference', sa.String(length=2000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_metadata_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_metadata_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_metadata_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_metadata_project_id'))

    op.drop_table('artifact_metadata')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_runs_experiment_specification_id'))
        batch_op.drop_index(batch_op.f('ix_runs_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_runs_environment_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_runs_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_runs_configuration_hash'))

    op.drop_table('runs')
    with op.batch_alter_table('environment_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_snapshots_environment_hash'))

    op.drop_table('environment_snapshots')
    # ### end Alembic commands ###
