"""add project status rejected

Revision ID: e633d3930fa8
Revises: 8eba82f8bdd1
Create Date: 2026-09-17 03:43:16.977852

Adds 'REJECTED' to the ProjectStatus vocabulary for the Phase 4 workflow
engine's `reject_project()` action, AND adds a real database-level CHECK
constraint to this column, which it never actually had (see
docs/PHASE4_WORKFLOW.md for how that gap was found: `native_enum=False`
alone renders as a plain VARCHAR with no CHECK constraint — SQLAlchemy's
Enum type requires `create_constraint=True` for that, which Phase 3's
original migration did not set for any of the 14 enum columns; only
this one is corrected here, since it already needs touching for
`REJECTED`). Alembic's autogenerate does not detect either of these
changes on its own for a `native_enum=False` Enum column, so this
migration is hand-written rather than autogenerated — `alter_column`
inside a batch context lets SQLite rebuild the table with the new CHECK
constraint (a no-op table rebuild on PostgreSQL, which enforces enum
values differently).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e633d3930fa8'
down_revision: Union[str, None] = '8eba82f8bdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OLD_VALUES = ("ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED")
_NEW_VALUES = ("ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED", "REJECTED")


def upgrade() -> None:
    with op.batch_alter_table("research_projects", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(*_OLD_VALUES, name="projectstatus", native_enum=False, length=32),
            type_=sa.Enum(*_NEW_VALUES, name="projectstatus", native_enum=False, length=32, create_constraint=True),
            existing_nullable=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("research_projects", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(*_NEW_VALUES, name="projectstatus", native_enum=False, length=32, create_constraint=True),
            type_=sa.Enum(*_OLD_VALUES, name="projectstatus", native_enum=False, length=32),
            existing_nullable=False,
        )
